<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use App\Models\CustomerOrder;

class CustomerOrdersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('customer_order') ->insert([
            [ //104153205
                'customers_id' => 1,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2022-01-23 00:00:00',
                'updated_at' => '2022-01-23 00:00:00',
            ],
            [ //104153206
                'customers_id' => 1,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2022-01-17 00:00:00',
                'updated_at' => '2022-01-17 00:00:00',
            ],
            [ //104153207
                'customers_id' => 1,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2022-01-18 00:00:00',
                'updated_at' => '2022-01-18 00:00:00',
            ],
            [ //104153208
                'customers_id' => 15,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2022-02-18 00:00:00',
                'updated_at' => '2022-02-18 00:00:00',
            ],
            [ //104153209
                'customers_id' => 19,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2022-03-20 00:00:00',
                'updated_at' => '2022-03-20 00:00:00',
            ],
            [ //104153210
                'customers_id' =>14,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2022-04-27 00:00:00',
                'updated_at' => '2022-04-27 00:00:00',
            ],
            [ //104153211
                'customers_id' => 6,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2022-05-9 00:00:00',
                'updated_at' => '2022-05-9 00:00:00',
            ],
            [ //104153212
                'customers_id' => 3,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2022-06-4 00:00:00',
                'updated_at' => '2022-06-4 00:00:00',
            ],
            [ //104153213
                'customers_id' => 3,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2022-06-5 00:00:00',
                'updated_at' => '2022-06-5 00:00:00',
            ],
            [ //104153214
                'customers_id' => 4,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2022-06-19 00:00:00',
                'updated_at' => '2022-06-19 00:00:00',
            ],
            [ //104153215
                'customers_id' => 5,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2022-07-13 00:00:00',
                'updated_at' => '2022-07-13 00:00:00',
            ],
            [ //104153216
                'customers_id' => 5,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2022-08-30 00:00:00',
                'updated_at' => '2022-08-30 00:00:00',
            ],
            [ //104153217
                'customers_id' => 6,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2022-09-28 00:00:00',
                'updated_at' => '2022-09-28 00:00:00',
            ],
            [ //104153218
                'customers_id' => 7,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Paid by Paypal',
                'payment_id' => Str::random(7),
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2022-10-28 00:00:00',
                'updated_at' => '2022-10-28 00:00:00',
            ],
            [ //104153219
                'customers_id' => 8,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Paid by Paypal',
                'payment_id' => Str::random(7),
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2022-11-15 00:00:00',
                'updated_at' => '2022-11-15 00:00:00',
            ],
            [ //104153220
                'customers_id' => 8,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Paid by Paypal',
                'payment_id' => Str::random(7),
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2022-11-15 00:00:00',
                'updated_at' => '2022-11-15 00:00:00',
            ],
            [ //104153221
                'customers_id' => 8,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Paid by Paypal',
                'payment_id' => Str::random(7),
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-1-4 00:00:00',
                'updated_at' => '2023-1-4 00:00:00',
            ],
            [ //104153222
                'customers_id' => 8,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-1-7 00:00:00',
                'updated_at' => '2023-1-7 00:00:00',
            ],
            [ //104153223
                'customers_id' => 9,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-1-11 00:00:00',
                'updated_at' => '2023-1-11 00:00:00',
            ],
            [ //104153224
                'customers_id' => 9,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Paid by Paypal',
                'payment_id' => null,
                'payment_id' => Str::random(7),
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-1-15 00:00:00',
                'updated_at' => '2023-1-15 00:00:00',
            ],
            [ //104153225
                'customers_id' => 9,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-1-18 00:00:00',
                'updated_at' => '2023-1-18 00:00:00',
            ],
            [ //104153226
                'customers_id' => 10,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-1-21 00:00:00',
                'updated_at' => '2023-1-21 00:00:00',
            ],
            [ //104153227
                'customers_id' => 10,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-1-27 00:00:00',
                'updated_at' => '2023-1-27 00:00:00',
            ],
            [ //104153228
                'customers_id' => 11,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Paid by Paypal',
                'payment_id' => Str::random(7),
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-1-31 00:00:00',
                'updated_at' => '2023-1-31 00:00:00',
            ],
            [ //104153229
                'customers_id' => 12,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Paid by Paypal',
                'payment_id' => Str::random(7),
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-2-3 00:00:00',
                'updated_at' => '2023-2-3 00:00:00',
            ],
            [ //104153230
                'customers_id' => 13,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Paid by Paypal',
                'payment_id' => Str::random(7),
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-2-5 00:00:00',
                'updated_at' => '2023-2-5 00:00:00',
            ],
            [ //104153231
                'customers_id' => 13,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Paid by Paypal',
                'payment_id' => Str::random(7),
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-2-8 00:00:00',
                'updated_at' => '2023-2-8 00:00:00',
            ],
            [ //104153232
                'customers_id' => 14,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-2-9 00:00:00',
                'updated_at' => '2023-2-9 00:00:00',
            ],
            [ //104153233
                'customers_id' => 14,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-2-14 00:00:00',
                'updated_at' => '2023-2-14 00:00:00',
            ],
            [ //104153234
                'customers_id' => 14,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-2-17 00:00:00',
                'updated_at' => '2023-2-17 00:00:00',
            ],
            [ //104153235
                'customers_id' => 15,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Paid by Paypal',
                'payment_id' => Str::random(7),
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-2-21 00:00:00',
                'updated_at' => '2023-2-21 00:00:00',
            ],
            [ //104153236
                'customers_id' => 15,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Paid by Paypal',
                'payment_id' => Str::random(7),
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-2-23 00:00:00',
                'updated_at' => '2023-2-23 00:00:00',
            ],
            [ //104153237
                'customers_id' => 16,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-2-25 00:00:00',
                'updated_at' => '2023-2-25 00:00:00',
            ],
            [ //104153238
                'customers_id' => 16,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-2-25 00:00:00',
                'updated_at' => '2023-2-25 00:00:00',
            ],
            [ //104153239
                'customers_id' => 18,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Paid by Paypal',
                'payment_id' => Str::random(7),
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-2-27 00:00:00',
                'updated_at' => '2023-2-27 00:00:00',
            ],
            [ //104153240
                'customers_id' => 19,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Paid by Paypal',
                'payment_id' => Str::random(7),
                'status' => 'Pending for Approval', //!!!!!!!!!!!! PENDING
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [ //104153241
                'customers_id' => 20,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Paid by Paypal',
                'payment_id' => Str::random(7),
                'status' => 'Pending for Approval',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [ //104153242
                'customers_id' => 20,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Paid by Paypal',
                'payment_id' => Str::random(7),
                'status' => 'Pending for Approval',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [ //104153243
                'customers_id' => 20,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Pending for Approval',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [ //104153244 - RECENT DATA 4 TEST - BEGIN
                'customers_id' => 9,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Pending for Approval',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [ //104153245
                'customers_id' => 7,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Paid by Paypal',
                'payment_id' => Str::random(7),
                'status' => 'Pending for Approval',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [ //104153246
                'customers_id' => 5,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Pending for Approval',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [ //104153247
                'customers_id' => 3,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Pending for Approval',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [ //104153248
                'customers_id' => 1,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Paid by Paypal',
                'payment_id' => Str::random(7),
                'status' => 'Pending for Approval',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], // - RECENT DATA 4 TEST - END !!!!!!!! PENDING END
            [ //104153249
                'customers_id' => 20,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-2-27 12:00:00',
                'updated_at' => '2023-2-27 12:00:00',
            ],
            [ //104153250
                'customers_id' => 19,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-2-28 15:00:00',
                'updated_at' => '2023-2-28 15:00:00',
            ],
            [ //104153251
                'customers_id' => 18,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-2-28 16:00:00',
                'updated_at' => '2023-2-28 16:00:00',
            ],
            [ //104153252
                'customers_id' => 21,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-2-28 19:00:00',
                'updated_at' => '2023-2-28 19:00:00',
            ],
            [ //104153253 - Cancelled
                'customers_id' => 1,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Cancelled',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => 1,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-3-1 00:00:00',
                'updated_at' => '2023-3-1 00:00:00',
            ],
            [ //104153254 - Cancelled
                'customers_id' => 3,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Cancelled',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => 1,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-3-2 00:00:00',
                'updated_at' => '2023-3-2 00:00:00',
            ],
            [ //104153255 - Cancelled
                'customers_id' => 4,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Cancelled',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => 1,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-3-3 00:00:00',
                'updated_at' => '2023-3-3 00:00:00',
            ],
            [ //104153256 - Cancelled
                'customers_id' => 4,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Cancelled',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => 2,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-3-4 00:00:00',
                'updated_at' => '2023-3-4 00:00:00',
            ],
            [ //104153257 - Cancelled
                'customers_id' => 5,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Cancelled',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => 3,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-3-5 00:00:00',
                'updated_at' => '2023-3-5 00:00:00',
            ],
            [ //104153258 - Cancelled
                'customers_id' => 6,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Cancelled',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => 3,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-3-6 00:00:00',
                'updated_at' => '2023-3-6 00:00:00',
            ],
            [ //104153259 - Cancelled
                'customers_id' => 7,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Cancelled',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => 4,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-3-7 00:00:00',
                'updated_at' => '2023-3-7 00:00:00',
            ],
            [ //104153260 - Cancelled
                'customers_id' => 7,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Cancelled',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => 5,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-3-8 00:00:00',
                'updated_at' => '2023-3-8 00:00:00',
            ],
            [ //104153261 - Cancelled
                'customers_id' => 7,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Cancelled',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => 6,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-3-9 00:00:00',
                'updated_at' => '2023-3-9 00:00:00',
            ],
            [ //104153262 - Cancelled
                'customers_id' => 8,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Cancelled',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => 7,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-3-10 00:00:00',
                'updated_at' => '2023-3-10 00:00:00',
            ],
            [ //104153263 - Cancelled
                'customers_id' => 9,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Cancelled',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => 8,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-3-10 00:00:00',
                'updated_at' => '2023-3-10 00:00:00',
            ],
            [ //104153264 - Rejected
                'customers_id' => 1,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Rejected',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => 'Stock Issue',
                'order_notes' => null,
                'created_at' => '2023-3-11 00:00:00',
                'updated_at' => '2023-3-11 00:00:00',
            ],
            [ //104153265 - Rejected
                'customers_id' => 10,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Rejected',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => 'Stock Issue',
                'order_notes' => null,
                'created_at' => '2023-3-11 00:00:00',
                'updated_at' => '2023-3-11 00:00:00',
            ],
            [ //104153266 - Rejected
                'customers_id' => 11,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Rejected',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => 'Stock Issue',
                'order_notes' => null,
                'created_at' => '2023-3-11 00:00:00',
                'updated_at' => '2023-3-11 00:00:00',
            ],
            [ //104153267 - Rejected
                'customers_id' => 12,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Rejected',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => 'Stock Issue',
                'order_notes' => null,
                'created_at' => '2023-3-11 00:00:00',
                'updated_at' => '2023-3-11 00:00:00',
            ],
            [ //104153268 - Rejected
                'customers_id' => 13,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Rejected',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => 'Stock Issue',
                'order_notes' => null,
                'created_at' => '2023-3-11 00:00:00',
                'updated_at' => '2023-3-11 00:00:00',
            ],
            [ //104153269 - Completed
                'customers_id' => 13,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-3-12 00:00:00',
                'updated_at' => '2023-3-12 00:00:00',
            ],
            [ //104153270 - Completed
                'customers_id' => 14,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-3-14 00:00:00',
                'updated_at' => '2023-3-14 00:00:00',
            ],
            [ //104153271 - Completed
                'customers_id' => 15,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-3-16 00:00:00',
                'updated_at' => '2023-3-16 00:00:00',
            ],
            [ //104153272 - Completed
                'customers_id' => 16,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-3-18 00:00:00',
                'updated_at' => '2023-3-18 00:00:00',
            ],
            [ //104153273 - Completed
                'customers_id' => 17,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-3-20 00:00:00',
                'updated_at' => '2023-3-20 00:00:00',
            ],
            [ //104153274 - Completed
                'customers_id' => 18,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-4-01 00:00:00',
                'updated_at' => '2023-4-01 00:00:00',
            ],
            [ //104153275 - Completed
                'customers_id' => 19,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-4-05 00:00:00',
                'updated_at' => '2023-4-05 00:00:00',
            ],
            [ //104153276 - Completed
                'customers_id' => 20,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-4-11 00:00:00',
                'updated_at' => '2023-4-11 00:00:00',
            ],
            [ //104153277 - Completed
                'customers_id' => 21,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-4-12 00:00:00',
                'updated_at' => '2023-4-12 00:00:00',
            ],
            [ //104153278 - Completed
                'customers_id' => 22,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-4-17 00:00:00',
                'updated_at' => '2023-4-17 00:00:00',
            ],
            [ //104153279 - Completed
                'customers_id' => 23,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-4-25 00:00:00',
                'updated_at' => '2023-4-25 00:00:00',
            ],
            [ //104153280 - Completed
                'customers_id' => 24,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-4-28 00:00:00',
                'updated_at' => '2023-4-28 00:00:00',
            ],
            [ //104153281 - Completed
                'customers_id' => 19,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-5-02 00:00:00',
                'updated_at' => '2023-5-02 00:00:00',
            ],
            [ //104153282 - Completed
                'customers_id' => 20,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-5-04 00:00:00',
                'updated_at' => '2023-5-04 00:00:00',
            ],
            [ //104153283 - Completed
                'customers_id' => 21,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-5-06 00:00:00',
                'updated_at' => '2023-5-06 00:00:00',
            ],
            [ //104153284 - Completed
                'customers_id' => 22,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-5-08 00:00:00',
                'updated_at' => '2023-5-08 00:00:00',
            ],
            [ //104153285 - Completed
                'customers_id' => 23,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-5-10 00:00:00',
                'updated_at' => '2023-5-10 00:00:00',
            ],
            [ //104153286 - Completed
                'customers_id' => 24,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-5-12 00:00:00',
                'updated_at' => '2023-5-12 00:00:00',
            ],
            [ //104153287 - Mark's 10 Order
                'customers_id' => 1,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'payment_id' => null,
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'remarks' => null,
                'cancellation_reason_id' => null,
                'cancellation_details' => null,
                'rejected_reason' => null,
                'order_notes' => null,
                'created_at' => '2023-5-15 00:00:00',
                'updated_at' => '2023-5-15 00:00:00',
            ],
        ]);
    }
}
