<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;
use App\Models\Customer;
class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('customers') ->insert([
            [//1
                'name' => 'Mark Joseph Manalo',
                'email' => 'markjosephmanalo1110@gmail.com',
                'email_verified_at' => now(),
                'phone_number' => '09452692274',
                'password' => bcrypt('Onepiece25!'),
                'gender' => 'Male',
                'birthday'=>'2001-06-08',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [//2
                'name' => 'Gene Vincent Soriano',
                'email' => 'programmingmind1110@gmail.com',
                'email_verified_at' => null,
                'phone_number' => '09452692274',
                'password' => bcrypt('Onepiece25!'),
                'gender' => 'Male',
                'birthday'=>'2001-06-08',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [//3
                'name' => 'Paul Reyes',
                'email' => 'pcreyes09@gmail.com',
                'email_verified_at' => now(),
                'phone_number' => '09452692274',
                'password' => bcrypt('Onepiece25!'),
                'gender' => 'Male',
                'birthday'=>'2001-06-08',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [//4
                'name' => 'Miguel Silverio',
                'email' => 'miguel2021@gmail.com',
                'email_verified_at' => now(),
                'phone_number' => '09452692274',
                'password' => bcrypt('Onepiece25!'),
                'gender' => 'Male',
                'birthday'=>'2001-06-08',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [//5
                'name' => 'John Zenmar Repil',
                'email' => 'jzenman21@gmail.com',
                'email_verified_at' => now(),
                'phone_number' => '09452692274',
                'password' => bcrypt('Onepiece25!'),
                'gender' => 'Male',
                'birthday'=>'2001-06-08',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [//6
                'name' => 'Aaron Delos Angeles',
                'email' => 'ponponpon@gmail.com',
                'email_verified_at' => now(),
                'phone_number' => '09452692274',
                'password' => bcrypt('Onepiece25!'),
                'gender' => 'Male',
                'birthday'=>'2001-06-08',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [//7
                'name' => 'Joshua Atos',
                'email' => 'joskykun@gmail.com',
                'email_verified_at' => now(),
                'phone_number' => '09452692274',
                'password' => bcrypt('Onepiece25!'),
                'gender' => 'Male',
                'birthday'=>'2001-06-08',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [//8
                'name' => 'Rence Tyler',
                'email' => 'TRence21@gmail.com',
                'email_verified_at' => now(),
                'phone_number' => '09452692274',
                'password' => bcrypt('Onepiece25!'),
                'gender' => 'Male',
                'birthday'=>'2001-06-08',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [//9
                'name' => 'Claire Mendoza',
                'email' => 'mendozaclaire11@gmail.com',
                'email_verified_at' => now(),
                'phone_number' => '09452692274',
                'password' => bcrypt('Onepiece25!'),
                'gender' => 'Female',
                'birthday'=>'2001-06-08',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [//10
                'name' => 'Nathaniel Recla',
                'email' => 'recla118@gmail.com',
                'email_verified_at' => now(),
                'phone_number' => '09452692274',
                'password' => bcrypt('Onepiece25!'),
                'gender' => 'Male',
                'birthday'=>'2001-06-08',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [//11
                'name' => 'Joy Tolentino',
                'email' => 'cupcakejj21@gmail.com',
                'email_verified_at' => now(),
                'phone_number' => '09452692274',
                'password' => bcrypt('Onepiece25!'),
                'gender' => 'Female',
                'birthday'=>'2001-06-08',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [//12
                'name' => 'Jerson Jake Tejada',
                'email' => 'jaket172@gmail.com',
                'email_verified_at' => now(),
                'phone_number' => '09452692274',
                'password' => bcrypt('Onepiece25!'),
                'gender' => 'Male',
                'birthday'=>'2001-06-08',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [//13
                'name' => 'Jahred Garcia',
                'email' => 'jahjahganda@gmail.com',
                'email_verified_at' => now(),
                'phone_number' => '09452692274',
                'password' => bcrypt('Onepiece25!'),
                'gender' => 'Male',
                'birthday'=>'2001-06-08',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [//14
                'name' => 'Oly Andreza',
                'email' => 'olygeh21@gmail.com',
                'email_verified_at' => now(),
                'phone_number' => '09452692274',
                'password' => bcrypt('Onepiece25!'),
                'gender' => 'Female',
                'birthday'=>'2001-06-08',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [//15
                'name' => 'Charm Belmonte',
                'email' => 'charring48@gmail.com',
                'email_verified_at' => now(),
                'phone_number' => '09452692274',
                'password' => bcrypt('Onepiece25!'),
                'gender' => 'Female',
                'birthday'=>'2001-06-08',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [//16
                'name' => 'Juliane Adaoag',
                'email' => 'jaaaa772@gmail.com',
                'email_verified_at' => now(),
                'phone_number' => '09452692274',
                'password' => bcrypt('Onepiece25!'),
                'gender' => 'Female',
                'birthday'=>'2001-06-08',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [//17
                'name' => 'Ericka Barrales',
                'email' => 'ErickaB281@gmail.com',
                'email_verified_at' => now(),
                'phone_number' => '09452692274',
                'password' => bcrypt('Onepiece25!'),
                'gender' => 'Female',
                'birthday'=>'2001-06-08',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [//18
                'name' => 'Dandy Andreza',
                'email' => 'sonnyboy@gmail.com',
                'email_verified_at' => now(),
                'phone_number' => '09452692274',
                'password' => bcrypt('Onepiece25!'),
                'gender' => 'Male',
                'birthday'=>'2001-06-08',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [//19
                'name' => 'Joel Montemayor',
                'email' => 'Montemayorjoel@gmail.com',
                'email_verified_at' => now(),
                'phone_number' => '09452692274',
                'password' => bcrypt('Onepiece25!'),
                'gender' => 'Male',
                'birthday'=>'2001-06-08',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [//20
                'name' => 'Francis Estabilo',
                'email' => 'France1233@gmail.com',
                'email_verified_at' => now(),
                'phone_number' => '09452692274',
                'password' => bcrypt('Onepiece25!'),
                'gender' => 'Male',
                'birthday'=>'2001-06-08',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [//21
                'name' => 'Cielo Fernandez',
                'email' => 'Cieloows66@gmail.com',
                'email_verified_at' => now(),
                'phone_number' => '09452692274',
                'password' => bcrypt('Onepiece25!'),
                'gender' => 'Male',
                'birthday'=>'2001-06-08',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);

        Customer::factory(100)->create();
    }
}
