<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use App\Models\CustomerOrder;

class CustomerOrdersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('customer_orders') ->insert([
            [
                'customers_id' => 1,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'created_at' => '2023-01-17 00:00:00',
                'updated_at' => '2023-01-17 00:00:00',
            ],
            [
                'customers_id' => 2,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'created_at' => '2023-01-17 00:00:00',
                'updated_at' => '2023-01-17 00:00:00',
            ],
            [
                'customers_id' => 3,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'created_at' => '2023-02-17 00:00:00',
                'updated_at' => '2023-02-17 00:00:00',
            ],
            [
                'customers_id' => 1,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'created_at' => '2023-02-17 00:00:00',
                'updated_at' => '2023-02-17 00:00:00',
            ],
            [
                'customers_id' => 4,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'status' => 'Pending for Approval',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'created_at' => '2023-03-17 00:00:00',
                'updated_at' => '2023-03-17 00:00:00',
            ],
            [
                'customers_id' => 5,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'created_at' => '2023-04-17 00:00:00',
                'updated_at' => '2023-04-17 00:00:00',
            ],
            [
                'customers_id' => 6,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'created_at' => '2023-05-17 00:00:00',
                'updated_at' => '2023-05-17 00:00:00',
            ],
            [
                'customers_id' => 1,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'status' => 'Pending for Approval',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'created_at' => '2023-06-17 00:00:00',
                'updated_at' => '2023-06-17 00:00:00',
            ],

            //8

            [
                'customers_id' => 7,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'created_at' => '2023-06-17 00:00:00',
                'updated_at' => '2023-06-17 00:00:00',
            ],
            [
                'customers_id' => 8,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'created_at' => '2023-07-17 00:00:00',
                'updated_at' => '2023-07-17 00:00:00',
            ],
            [
                'customers_id' => 9,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'created_at' => '2023-08-17 00:00:00',
                'updated_at' => '2023-08-17 00:00:00',
            ],
            [
                'customers_id' => 10,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'created_at' => '2023-09-17 00:00:00',
                'updated_at' => '2023-09-17 00:00:00',
            ],
            [
                'customers_id' => 11,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'status' => 'Pending for Approval',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'created_at' => '2023-10-17 00:00:00',
                'updated_at' => '2023-10-17 00:00:00',
            ],
            [
                'customers_id' => 12,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'created_at' => '2023-11-17 00:00:00',
                'updated_at' => '2023-11-17 00:00:00',
            ],
            [
                'customers_id' => 2,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'status' => 'Completed',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'created_at' => '2023-12-17 00:00:00',
                'updated_at' => '2023-12-17 00:00:00',
            ],
            [
                'customers_id' => 3,
                'shippingfee' =>100.00 ,
                'mode_of_payment' => 'Cash On Delivery',
                'status' => 'Pending for Approval',
                'received_by' => 'Mark Joseph Manalo',
                'phone_number' => '09369332354',
                'notes' => 'Yellow Gate',
                'house' => '283 Ramos Compound Baesa Quezon City',
                'province' => 'Second District(NCR)',
                'city' => 'Quezon City',
                'barangay' => "Baesa",
                'created_at' => '2023-06-17 00:00:00',
                'updated_at' => '2023-06-17 00:00:00',
            ],
        ]);
    }
}
