<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class InventoryHistorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('inventory_history') ->insert([
            [
            'product_id' => '1',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-2)',
            'latest_value' => '10',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153205,
            'created_at' => '2022-01-23 00:00:00',
            'updated_at' => '2022-01-23 00:00:00',
            ],
            [
            'product_id' => '2',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-2)',
            'latest_value' => '10',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153205,
            'created_at' => '2022-01-23 00:00:00',
            'updated_at' => '2022-01-23 00:00:00',
            ],
            [
            'product_id' => '7',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-5)',
            'latest_value' => '95',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153206,
            'created_at' => '2022-01-17 00:00:00',
            'updated_at' => '2022-01-17 00:00:00',
            ],
            [
            'product_id' => '139',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-3)',
            'latest_value' => '37',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153207,
            'created_at' => '2022-01-18 00:00:00',
            'updated_at' => '2022-01-18 00:00:00',
            ],
            [ //5
            'product_id' => '7',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-5)',
            'latest_value' => '90',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153207,
            'created_at' => '2022-01-18 00:00:00',
            'updated_at' => '2022-01-18 00:00:00',
            ],
            [
            'product_id' => '7',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-5)',
            'latest_value' => '85',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153208,
            'created_at' => '2022-02-18 00:00:00',
            'updated_at' => '2022-02-18 00:00:00',
            ],
            [
            'product_id' => '25',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-3)',
            'latest_value' => '37',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153208,
            'created_at' => '2022-02-18 00:00:00',
            'updated_at' => '2022-02-18 00:00:00',
            ],
            [
            'product_id' => '132',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-8)',
            'latest_value' => '32',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153209,
            'created_at' => '2022-03-20 00:00:00',
            'updated_at' => '2022-03-20 00:00:00',
            ],
            [
            'product_id' => '9',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-3)',
            'latest_value' => '17',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153209,
            'created_at' => '2022-03-20 00:00:00',
            'updated_at' => '2022-03-20 00:00:00',
            ],
            [//10
            'product_id' => '129',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-10)',
            'latest_value' => '30',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153210,
            'created_at' => '2022-04-27 00:00:00',
            'updated_at' => '2022-04-27 00:00:00',
            ],
            [
            'product_id' => '19',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-4)',
            'latest_value' => '36',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153211,
            'created_at' => '2022-04-27 00:00:00',
            'updated_at' => '2022-04-27 00:00:00',
            ],
            [
            'product_id' => '7',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-3)',
            'latest_value' => '82',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153212,
            'created_at' => '2022-05-9 00:00:00',
            'updated_at' => '2022-05-9 00:00:00',
            ],
            [
            'product_id' => '24',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-3)',
            'latest_value' => '37',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153213,
            'created_at' => '2022-06-5 00:00:00',
            'updated_at' => '2022-06-5 00:00:00',
            ],
            [
            'product_id' => '7',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-4)',
            'latest_value' => '78',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153214,
            'created_at' => '2022-06-19 00:00:00',
            'updated_at' => '2022-06-19 00:00:00',
            ],
            [//15
            'product_id' => '101',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-5)',
            'latest_value' => '35',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153215,
            'created_at' => '2022-07-13 00:00:00',
            'updated_at' => '2022-07-13 00:00:00',
            ],
            [
            'product_id' => '7',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-2)',
            'latest_value' => '76',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153215,
            'created_at' => '2022-07-13 00:00:00',
            'updated_at' => '2022-07-13 00:00:00',
            ],
            [
            'product_id' => '108',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '4',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153216,
            'created_at' => '2022-08-30 00:00:00',
            'updated_at' => '2022-08-30 00:00:00',
            ],
            [
            'product_id' => '111',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-6)',
            'latest_value' => '34',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153216,
            'created_at' => '2022-08-30 00:00:00',
            'updated_at' => '2022-08-30 00:00:00',
            ],
            [
            'product_id' => '7',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-9)',
            'latest_value' => '67',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153217,
            'created_at' => '2022-09-28 00:00:00',
            'updated_at' => '2022-09-28 00:00:00',
            ],
            [//20
            'product_id' => '7',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '66',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153218,
            'created_at' => '2022-10-28 00:00:00',
            'updated_at' => '2022-10-28 00:00:00',
            ],
            [
            'product_id' => '7',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '65',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153219,
            'created_at' => '2022-11-15 00:00:00',
            'updated_at' => '2022-11-15 00:00:00',
            ],
            [
            'product_id' => '87',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-2)',
            'latest_value' => '38',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153220,
            'created_at' => '2022-1-14 00:00:00',
            'updated_at' => '2022-1-14 00:00:00',
            ],
            [
            'product_id' => '88',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-3)',
            'latest_value' => '37',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153220,
            'created_at' => '2022-1-14 00:00:00',
            'updated_at' => '2022-1-14 00:00:00',
            ],
            [
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-3)',
            'latest_value' => '97',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153220,
            'created_at' => '2022-1-14 00:00:00',
            'updated_at' => '2022-1-14 00:00:00',
            ],
            [//25
            'product_id' => '44',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-3)',
            'latest_value' => '37',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153221,
            'created_at' => '2023-1-4 00:00:00',
            'updated_at' => '2023-1-4 00:00:00',
            ],
            [
            'product_id' => '61',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '39',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153222,
            'created_at' => '2023-1-7 00:00:00',
            'updated_at' => '2023-1-7 00:00:00',
            ],
            [
            'product_id' => '7',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '64',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153223,
            'created_at' => '2023-1-11 00:00:00',
            'updated_at' => '2023-1-11 00:00:00',
            ],
            [
            'product_id' => '6',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-15)',
            'latest_value' => '5',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153224,
            'created_at' => '2023-1-15 00:00:00',
            'updated_at' => '2023-1-15 00:00:00',
            ],
            [
            'product_id' => '5',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-2)',
            'latest_value' => '13',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153224,
            'created_at' => '2023-1-15 00:00:00',
            'updated_at' => '2023-1-15 00:00:00',
            ],
            [//30
            'product_id' => '57',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '39',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153225,
            'created_at' => '2023-1-18 00:00:00',
            'updated_at' => '2023-1-18 00:00:00',
            ],
            [
            'product_id' => '74',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '39',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153226,
            'created_at' => '2023-1-21 00:00:00',
            'updated_at' => '2023-1-21 00:00:00',
            ],
            [
            'product_id' => '7',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '63',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153227,
            'created_at' => '2023-1-27 00:00:00',
            'updated_at' => '2023-1-27 00:00:00',
            ],
            [
            'product_id' => '7',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '62',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153228,
            'created_at' => '2023-1-31 00:00:00',
            'updated_at' => '2023-1-31 00:00:00',
            ],
            [
            'product_id' => '7',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-20)',
            'latest_value' => '42',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153229,
            'created_at' => '2023-2-3 00:00:00',
            'updated_at' => '2023-2-3 00:00:00',
            ],
            [//35
            'product_id' => '7',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-5)',
            'latest_value' => '37',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153230,
            'created_at' => '2023-2-5 00:00:00',
            'updated_at' => '2023-2-5 00:00:00',
            ],
            [
            'product_id' => '108',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '3',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153231,
            'created_at' => '2023-2-8 00:00:00',
            'updated_at' => '2023-2-8 00:00:00',
            ],
            [
            'product_id' => '138',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-10)',
            'latest_value' => '30',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153231,
            'created_at' => '2023-2-8 00:00:00',
            'updated_at' => '2023-2-8 00:00:00',
            ],
            [
            'product_id' => '137',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-4)',
            'latest_value' => '36',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153231,
            'created_at' => '2023-2-8 00:00:00',
            'updated_at' => '2023-2-8 00:00:00',
            ],
            [
            'product_id' => '30',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-2)',
            'latest_value' => '38',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153231,
            'created_at' => '2023-2-8 00:00:00',
            'updated_at' => '2023-2-8 00:00:00',
            ],
            [//40
            'product_id' => '45',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '39',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153232,
            'created_at' => '2023-2-9 00:00:00',
            'updated_at' => '2023-2-9 00:00:00',
            ],
            [
            'product_id' => '62',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '39',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153233,
            'created_at' => '2023-2-14 00:00:00',
            'updated_at' => '2023-2-14 00:00:00',
            ],
            [
            'product_id' => '7',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-3)',
            'latest_value' => '34',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153234,
            'created_at' => '2023-2-17 00:00:00',
            'updated_at' => '2023-2-17 00:00:00',
            ],
            [
            'product_id' => '7',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-8)',
            'latest_value' => '26',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153235,
            'created_at' => '2023-2-21 00:00:00',
            'updated_at' => '2023-2-21 00:00:00',
            ],
            [
            'product_id' => '113',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-2)',
            'latest_value' => '38',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153236,
            'created_at' => '2023-2-23 00:00:00',
            'updated_at' => '2023-2-23 00:00:00',
            ],
            [//45
            'product_id' => '7',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '25',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153237,
            'created_at' => '2023-2-25 00:00:00',
            'updated_at' => '2023-2-25 00:00:00',
            ],
            [
            'product_id' => '78',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-2)',
            'latest_value' => '38',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153238,
            'created_at' => '2023-2-26 00:00:00',
            'updated_at' => '2023-2-26 00:00:00',
            ],
            [
            'product_id' => '79',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-2)',
            'latest_value' => '38',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153238,
            'created_at' => '2023-2-26 00:00:00',
            'updated_at' => '2023-2-26 00:00:00',
            ],
            [
            'product_id' => '7',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '24',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153239,
            'created_at' => '2023-2-27 00:00:00',
            'updated_at' => '2023-2-27 00:00:00',
            ],
            [
            'product_id' => '112',
            'activity' => 'Customer Order with Order ID of ', //pending
            'adjusted_by' => '',
            'operation_value' => '(-12)',
            'latest_value' => '28',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153240,
            'created_at' => '2023-2-26 00:00:00',
            'updated_at' => '2023-2-26 00:00:00',
            ],
            [//50
            'product_id' => '132',
            'activity' => 'Customer Order with Order ID of ', //pending
            'adjusted_by' => '',
            'operation_value' => '(-12)',
            'latest_value' => '20',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153241,
            'created_at' => '2023-2-27 00:00:00',
            'updated_at' => '2023-2-27 00:00:00',
            ],
            [
            'product_id' => '97',
            'activity' => 'Customer Order with Order ID of ', //pending
            'adjusted_by' => '',
            'operation_value' => '(-4)',
            'latest_value' => '36',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153242,
            'created_at' => '2023-2-23 00:00:00',
            'updated_at' => '2023-2-23 00:00:00',
            ],
            [
            'product_id' => '40',
            'activity' => 'Customer Order with Order ID of ', //pending
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '39',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153243,
            'created_at' => '2023-2-23 00:00:00',
            'updated_at' => '2023-2-23 00:00:00',
            ],
            [
            'product_id' => '101',
            'activity' => 'Customer Order with Order ID of ', //pending
            'adjusted_by' => '',
            'operation_value' => '(-2)',
            'latest_value' => '33',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153244,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            ],
            [
            'product_id' => '98',
            'activity' => 'Customer Order with Order ID of ', //pending
            'adjusted_by' => '',
            'operation_value' => '(-2)',
            'latest_value' => '33',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153245,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            ],
            [
            'product_id' => '53',
            'activity' => 'Customer Order with Order ID of ', //pending
            'adjusted_by' => '',
            'operation_value' => '(-2)',
            'latest_value' => '38',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153246,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            ],
            [
            'product_id' => '14',
            'activity' => 'Customer Order with Order ID of ', //pending
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '39',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153247,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            ],
            [
            'product_id' => '33',
            'activity' => 'Customer Order with Order ID of ', //pending
            'adjusted_by' => '',
            'operation_value' => '(-2)',
            'latest_value' => '38',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153248,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
            ],
            [
            'product_id' => '7',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-2)',
            'latest_value' => '22',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153249,
            'created_at' => '2023-2-27 12:00:00',
            'updated_at' => '2023-2-27 12:00:00',
            ],
            [
            'product_id' => '7',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-3)',
            'latest_value' => '19',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153250,
            'created_at' => '2023-2-28 15:00:00',
            'updated_at' => '2023-2-28 15:00:00',
            ],
            [
            'product_id' => '7',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '18',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153251,
            'created_at' => '2023-2-28 16:00:00',
            'updated_at' => '2023-2-28 16:00:00',
            ],
            [
            'product_id' => '7',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-4)',
            'latest_value' => '14',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153252,
            'created_at' => '2023-2-28 19:00:00',
            'updated_at' => '2023-2-28 19:00:00',
            ],// end of bib + random
            [//applicator tips - begin
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '99',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153207,
            'created_at' => '2022-01-18 00:00:00',
            'updated_at' => '2022-01-18 00:00:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '98',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153212,
            'created_at' => '2022-06-4 00:00:00',
            'updated_at' => '2022-06-4 00:00:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '97',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153214,
            'created_at' => '2022-06-19 00:00:00',
            'updated_at' => '2022-06-19 00:00:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '96',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153215,
            'created_at' => '2022-07-13 00:00:00',
            'updated_at' => '2022-07-13 00:00:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '95',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153217,
            'created_at' => '2022-09-28 00:00:00',
            'updated_at' => '2022-09-28 00:00:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '94',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153218,
            'created_at' => '2022-10-28 00:00:00',
            'updated_at' => '2022-10-28 00:00:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '93',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153219,
            'created_at' => '2022-11-15 00:00:00',
            'updated_at' => '2022-11-15 00:00:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '92',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153223,
            'created_at' => '2023-1-11 00:00:00',
            'updated_at' => '2023-1-11 00:00:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '91',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153227,
            'created_at' => '2023-1-27 00:00:00',
            'updated_at' => '2023-1-27 00:00:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '90',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153228,
            'created_at' => '2023-1-31 00:00:00',
            'updated_at' => '2023-1-31 00:00:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '89',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153229,
            'created_at' => '2023-2-3 00:00:00',
            'updated_at' => '2023-2-3 00:00:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '88',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153230,
            'created_at' => '2023-2-5 00:00:00',
            'updated_at' => '2023-2-5 00:00:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '87',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153234,
            'created_at' => '2023-2-17 00:00:00',
            'updated_at' => '2023-2-17 00:00:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '86',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153235,
            'created_at' => '2023-2-21 00:00:00',
            'updated_at' => '2023-2-21 00:00:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '85',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153237,
            'created_at' => '2023-2-25 00:00:00',
            'updated_at' => '2023-2-25 00:00:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '84',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153239,
            'created_at' => '2023-2-27 00:00:00',
            'updated_at' => '2023-2-27 00:00:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '83',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153249,
            'created_at' => '2023-2-27 12:00:00',
            'updated_at' => '2023-2-27 12:00:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '82',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153250,
            'created_at' => '2023-2-28 15:00:00',
            'updated_at' => '2023-2-28 15:00:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '81',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153251,
            'created_at' => '2023-2-28 16:00:00',
            'updated_at' => '2023-2-28 16:00:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '80',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153252,
            'created_at' => '2023-2-28 19:00:00',
            'updated_at' => '2023-2-28 19:00:00',
            ],//applicator tips - end
            [//armstrong castone - begin
            'product_id' => '13',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '99',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153212,
            'created_at' => '2022-06-4 00:00:00',
            'updated_at' => '2022-06-4 00:00:00',
            ],
            [
            'product_id' => '13',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '98',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153214,
            'created_at' => '2022-06-19 00:00:00',
            'updated_at' => '2022-06-19 00:00:00',
            ],
            [
            'product_id' => '13',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '97',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153215,
            'created_at' => '2022-07-13 00:00:00',
            'updated_at' => '2022-07-13 00:00:00',
            ],
            [
            'product_id' => '13',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '96',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153217,
            'created_at' => '2022-09-28 00:00:00',
            'updated_at' => '2022-09-28 00:00:00',
            ],
            [
            'product_id' => '13',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '95',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153218,
            'created_at' => '2022-10-28 00:00:00',
            'updated_at' => '2022-10-28 00:00:00',
            ],
            [
            'product_id' => '13',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '94',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153219,
            'created_at' => '2022-11-15 00:00:00',
            'updated_at' => '2022-11-15 00:00:00',
            ],
            [
            'product_id' => '13',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '93',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153223,
            'created_at' => '2023-1-11 00:00:00',
            'updated_at' => '2023-1-11 00:00:00',
            ],
            [
            'product_id' => '13',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '92',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153227,
            'created_at' => '2023-1-27 00:00:00',
            'updated_at' => '2023-1-27 00:00:00',
            ],
            [
            'product_id' => '13',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '91',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153228,
            'created_at' => '2023-1-31 00:00:00',
            'updated_at' => '2023-1-31 00:00:00',
            ],
            [
            'product_id' => '13',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '90',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153229,
            'created_at' => '2023-2-3 00:00:00',
            'updated_at' => '2023-2-3 00:00:00',
            ],
            [
            'product_id' => '13',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '89',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153230,
            'created_at' => '2023-2-5 00:00:00',
            'updated_at' => '2023-2-5 00:00:00',
            ],
            [
            'product_id' => '13',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '88',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153234,
            'created_at' => '2023-2-17 00:00:00',
            'updated_at' => '2023-2-17 00:00:00',
            ],
            [
            'product_id' => '13',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '87',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153235,
            'created_at' => '2023-2-21 00:00:00',
            'updated_at' => '2023-2-21 00:00:00',
            ],
            [
            'product_id' => '13',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '86',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153237,
            'created_at' => '2023-2-25 00:00:00',
            'updated_at' => '2023-2-25 00:00:00',
            ],
            [
            'product_id' => '13',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '85',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153239,
            'created_at' => '2023-2-27 00:00:00',
            'updated_at' => '2023-2-27 00:00:00',
            ],
            [
            'product_id' => '13',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '84',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153249,
            'created_at' => '2023-2-27 12:00:00',
            'updated_at' => '2023-2-27 12:00:00',
            ],
            [
            'product_id' => '13',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '83',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153250,
            'created_at' => '2023-2-28 15:00:00',
            'updated_at' => '2023-2-28 15:00:00',
            ],
            [
            'product_id' => '13',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '82',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153251,
            'created_at' => '2023-2-28 16:00:00',
            'updated_at' => '2023-2-28 16:00:00',
            ],
            [
            'product_id' => '13',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '81',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153252,
            'created_at' => '2023-2-28 19:00:00',
            'updated_at' => '2023-2-28 19:00:00',
            ],//armstrong castone - end
            [//armstrong diestone - begin
            'product_id' => '12',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '99',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153212,
            'created_at' => '2022-06-4 00:00:00',
            'updated_at' => '2022-06-4 00:00:00',
            ],
            [
            'product_id' => '12',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '98',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153214,
            'created_at' => '2022-06-19 00:00:00',
            'updated_at' => '2022-06-19 00:00:00',
            ],
            [
            'product_id' => '12',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '97',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153215,
            'created_at' => '2022-07-13 00:00:00',
            'updated_at' => '2022-07-13 00:00:00',
            ],
            [
            'product_id' => '12',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '96',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153217,
            'created_at' => '2022-09-28 00:00:00',
            'updated_at' => '2022-09-28 00:00:00',
            ],
            [
            'product_id' => '12',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '95',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153218,
            'created_at' => '2022-10-28 00:00:00',
            'updated_at' => '2022-10-28 00:00:00',
            ],
            [
            'product_id' => '12',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '94',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153219,
            'created_at' => '2022-11-15 00:00:00',
            'updated_at' => '2022-11-15 00:00:00',
            ],
            [
            'product_id' => '12',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '93',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153223,
            'created_at' => '2023-1-11 00:00:00',
            'updated_at' => '2023-1-11 00:00:00',
            ],
            [
            'product_id' => '12',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '92',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153227,
            'created_at' => '2023-1-27 00:00:00',
            'updated_at' => '2023-1-27 00:00:00',
            ],
            [
            'product_id' => '12',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '91',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153228,
            'created_at' => '2023-1-31 00:00:00',
            'updated_at' => '2023-1-31 00:00:00',
            ],
            [
            'product_id' => '12',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '90',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153229,
            'created_at' => '2023-2-3 00:00:00',
            'updated_at' => '2023-2-3 00:00:00',
            ],
            [
            'product_id' => '12',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '89',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153230,
            'created_at' => '2023-2-5 00:00:00',
            'updated_at' => '2023-2-5 00:00:00',
            ],
            [
            'product_id' => '12',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '88',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153234,
            'created_at' => '2023-2-17 00:00:00',
            'updated_at' => '2023-2-17 00:00:00',
            ],
            [
            'product_id' => '12',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '87',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153235,
            'created_at' => '2023-2-21 00:00:00',
            'updated_at' => '2023-2-21 00:00:00',
            ],
            [
            'product_id' => '12',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '86',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153237,
            'created_at' => '2023-2-25 00:00:00',
            'updated_at' => '2023-2-25 00:00:00',
            ],
            [
            'product_id' => '12',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '85',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153239,
            'created_at' => '2023-2-27 00:00:00',
            'updated_at' => '2023-2-27 00:00:00',
            ],
            [
            'product_id' => '12',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '84',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153249,
            'created_at' => '2023-2-27 12:00:00',
            'updated_at' => '2023-2-27 12:00:00',
            ],
            [
            'product_id' => '12',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '83',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153250,
            'created_at' => '2023-2-28 15:00:00',
            'updated_at' => '2023-2-28 15:00:00',
            ],
            [
            'product_id' => '12',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '82',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153251,
            'created_at' => '2023-2-28 16:00:00',
            'updated_at' => '2023-2-28 16:00:00',
            ],
            [
            'product_id' => '12',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '81',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153252,
            'created_at' => '2023-2-28 19:00:00',
            'updated_at' => '2023-2-28 19:00:00',
            ],//armstrong diestone - end
            [//articaine - begin
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '96',
            'purchase_order_id' => NULL,
			'customer_order_id' => 104153212,
            'created_at' => '2022-06-4 00:00:00',
            'updated_at' => '2022-06-4 00:00:00',
            ],
            [
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '95',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153214,
            'created_at' => '2022-06-19 00:00:00',
            'updated_at' => '2022-06-19 00:00:00',
            ],
            [
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '94',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153215,
            'created_at' => '2022-07-13 00:00:00',
            'updated_at' => '2022-07-13 00:00:00',
            ],
            [
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '93',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153217,
            'created_at' => '2022-09-28 00:00:00',
            'updated_at' => '2022-09-28 00:00:00',
            ],
            [
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '92',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153218,
            'created_at' => '2022-10-28 00:00:00',
            'updated_at' => '2022-10-28 00:00:00',
            ],
            [
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '91',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153219,
            'created_at' => '2022-11-15 00:00:00',
            'updated_at' => '2022-11-15 00:00:00',
            ],
            [
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '90',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153223,
            'created_at' => '2023-1-11 00:00:00',
            'updated_at' => '2023-1-11 00:00:00',
            ],
            [
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '89',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153227,
            'created_at' => '2023-1-27 00:00:00',
            'updated_at' => '2023-1-27 00:00:00',
            ],
            [
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '88',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153228,
            'created_at' => '2023-1-31 00:00:00',
            'updated_at' => '2023-1-31 00:00:00',
            ],
            [
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '87',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153229,
            'created_at' => '2023-2-3 00:00:00',
            'updated_at' => '2023-2-3 00:00:00',
            ],
            [
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '86',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153230,
            'created_at' => '2023-2-5 00:00:00',
            'updated_at' => '2023-2-5 00:00:00',
            ],
            [
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '85',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153234,
            'created_at' => '2023-2-17 00:00:00',
            'updated_at' => '2023-2-17 00:00:00',
            ],
            [
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '84',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153235,
            'created_at' => '2023-2-21 00:00:00',
            'updated_at' => '2023-2-21 00:00:00',
            ],
            [
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '83',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153237,
            'created_at' => '2023-2-25 00:00:00',
            'updated_at' => '2023-2-25 00:00:00',
            ],
            [
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '82',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153239,
            'created_at' => '2023-2-27 00:00:00',
            'updated_at' => '2023-2-27 00:00:00',
            ],
            [
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '81',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153249,
            'created_at' => '2023-2-27 12:00:00',
            'updated_at' => '2023-2-27 12:00:00',
            ],
            [
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '80',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153250,
            'created_at' => '2023-2-28 15:00:00',
            'updated_at' => '2023-2-28 15:00:00',
            ],
            [
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '79',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153251,
            'created_at' => '2023-2-28 16:00:00',
            'updated_at' => '2023-2-28 16:00:00',
            ],
            [
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '78',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153252,
            'created_at' => '2023-2-28 19:00:00',
            'updated_at' => '2023-2-28 19:00:00',
            ],//articaine - end
            [//articulating paper - begin
            'product_id' => '49',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '99',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153212,
            'created_at' => '2022-06-4 00:00:00',
            'updated_at' => '2022-06-4 00:00:00',
            ],
            [
            'product_id' => '49',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '98',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153214,
            'created_at' => '2022-06-19 00:00:00',
            'updated_at' => '2022-06-19 00:00:00',
            ],
            [
            'product_id' => '49',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '97',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153215,
            'created_at' => '2022-07-13 00:00:00',
            'updated_at' => '2022-07-13 00:00:00',
            ],
            [
            'product_id' => '49',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '96',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153217,
            'created_at' => '2022-09-28 00:00:00',
            'updated_at' => '2022-09-28 00:00:00',
            ],
            [
            'product_id' => '49',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '95',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153218,
            'created_at' => '2022-10-28 00:00:00',
            'updated_at' => '2022-10-28 00:00:00',
            ],
            [
            'product_id' => '49',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '94',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153219,
            'created_at' => '2022-11-15 00:00:00',
            'updated_at' => '2022-11-15 00:00:00',
            ],
            [
            'product_id' => '49',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '93',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153223,
            'created_at' => '2023-1-11 00:00:00',
            'updated_at' => '2023-1-11 00:00:00',
            ],
            [
            'product_id' => '49',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '92',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153227,
            'created_at' => '2023-1-27 00:00:00',
            'updated_at' => '2023-1-27 00:00:00',
            ],
            [
            'product_id' => '49',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '91',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153228,
            'created_at' => '2023-1-31 00:00:00',
            'updated_at' => '2023-1-31 00:00:00',
            ],
            [
            'product_id' => '49',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '90',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153229,
            'created_at' => '2023-2-3 00:00:00',
            'updated_at' => '2023-2-3 00:00:00',
            ],
            [
            'product_id' => '49',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '89',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153230,
            'created_at' => '2023-2-5 00:00:00',
            'updated_at' => '2023-2-5 00:00:00',
            ],
            [
            'product_id' => '49',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '88',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153234,
            'created_at' => '2023-2-17 00:00:00',
            'updated_at' => '2023-2-17 00:00:00',
            ],
            [
            'product_id' => '49',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '87',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153235,
            'created_at' => '2023-2-21 00:00:00',
            'updated_at' => '2023-2-21 00:00:00',
            ],
            [
            'product_id' => '49',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '86',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153237,
            'created_at' => '2023-2-25 00:00:00',
            'updated_at' => '2023-2-25 00:00:00',
            ],
            [
            'product_id' => '49',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '85',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153239,
            'created_at' => '2023-2-27 00:00:00',
            'updated_at' => '2023-2-27 00:00:00',
            ],
            [
            'product_id' => '49',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '84',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153249,
            'created_at' => '2023-2-27 12:00:00',
            'updated_at' => '2023-2-27 12:00:00',
            ],
            [
            'product_id' => '49',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '83',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153250,
            'created_at' => '2023-2-28 15:00:00',
            'updated_at' => '2023-2-28 15:00:00',
            ],
            [
            'product_id' => '49',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '82',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153251,
            'created_at' => '2023-2-28 16:00:00',
            'updated_at' => '2023-2-28 16:00:00',
            ],
            [
            'product_id' => '49',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '81',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153252,
            'created_at' => '2023-2-28 19:00:00',
            'updated_at' => '2023-2-28 19:00:00',
            ],//articulating paper - end
            [//Cancelled/Rejected Products - Begin
            'product_id' => '7',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(+2)',
            'latest_value' => '14',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153253,
            'created_at' => '2023-3-2 00:00:00',
            'updated_at' => '2023-3-2 00:00:00',
            ],
            [
            'product_id' => '7',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-2)',
            'latest_value' => '12',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153253,
            'created_at' => '2023-3-2 00:00:00',
            'updated_at' => '2023-3-2 00:00:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(+2)',
            'latest_value' => '80',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153253,
            'created_at' => '2023-3-2 00:00:00',
            'updated_at' => '2023-3-2 00:00:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-2)',
            'latest_value' => '78',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153253,
            'created_at' => '2023-3-2 00:00:00',
            'updated_at' => '2023-3-2 00:00:00',
            ],
            [
            'product_id' => '108',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(+1)',
            'latest_value' => '3',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153254,
            'created_at' => '2023-3-2 14:45:00',
            'updated_at' => '2023-3-2 14:45:00',
            ],
            [
            'product_id' => '108',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '2',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153254,
            'created_at' => '2023-3-2 14:45:00',
            'updated_at' => '2023-3-2 14:45:00',
            ],
            [
            'product_id' => '12',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(+1)',
            'latest_value' => '81',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153255,
            'created_at' => '2023-3-3 09:00:00',
            'updated_at' => '2023-3-3 09:00:00',
            ],
            [
            'product_id' => '12',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '80',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153255,
            'created_at' => '2023-3-3 09:00:00',
            'updated_at' => '2023-3-3 09:00:00',
            ],
            [
            'product_id' => '13',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(+1)',
            'latest_value' => '81',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153256,
            'created_at' => '2023-3-4 12:00:00',
            'updated_at' => '2023-3-4 12:00:00',
            ],
            [
            'product_id' => '13',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '80',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153256,
            'created_at' => '2023-3-4 12:00:00',
            'updated_at' => '2023-3-4 12:00:00',
            ],
            [
            'product_id' => '13',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(+3)',
            'latest_value' => '81',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153257,
            'created_at' => '2023-3-5 09:00:00',
            'updated_at' => '2023-3-5 09:00:00',
            ],
            [
            'product_id' => '13',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-3)',
            'latest_value' => '78',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153257,
            'created_at' => '2023-3-5 09:00:00',
            'updated_at' => '2023-3-5 09:00:00',
            ],
            [
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(+1)',
            'latest_value' => '78',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153258,
            'created_at' => '2023-3-6 07:00:00',
            'updated_at' => '2023-3-6 07:00:00',
            ],
            [
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '77',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153258,
            'created_at' => '2023-3-6 07:00:00',
            'updated_at' => '2023-3-6 07:00:00',
            ],
            [
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(+25)',
            'latest_value' => '78',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153259,
            'created_at' => '2023-3-7 16:10:00',
            'updated_at' => '2023-3-7 16:10:00',
            ],
            [
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-25)',
            'latest_value' => '53',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153259,
            'created_at' => '2023-3-7 16:10:00',
            'updated_at' => '2023-3-7 16:10:00',
            ],
            [
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(+5)',
            'latest_value' => '78',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153260,
            'created_at' => '2023-3-8 07:30:00',
            'updated_at' => '2023-3-8 07:30:00',
            ],
            [
            'product_id' => '90',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-5)',
            'latest_value' => '73',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153260,
            'created_at' => '2023-3-8 07:30:00',
            'updated_at' => '2023-3-8 07:30:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(+1)',
            'latest_value' => '80',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153261,
            'created_at' => '2023-3-9 07:30:00',
            'updated_at' => '2023-3-9 07:30:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '79',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153261,
            'created_at' => '2023-3-9 07:30:00',
            'updated_at' => '2023-3-9 07:30:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(+1)',
            'latest_value' => '80',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153262,
            'created_at' => '2023-3-10 07:30:00',
            'updated_at' => '2023-3-10 07:30:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '79',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153262,
            'created_at' => '2023-3-10 07:30:00',
            'updated_at' => '2023-3-10 07:30:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(+1)',
            'latest_value' => '80',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153263,
            'created_at' => '2023-3-10 15:53:00',
            'updated_at' => '2023-3-10 15:53:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '79',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153263,
            'created_at' => '2023-3-10 15:53:00',
            'updated_at' => '2023-3-10 15:53:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => 'Mark Joseph Manalo',
            'operation_value' => '(+1)',
            'latest_value' => '80',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153264,
            'created_at' => '2023-3-11 08:32:00',
            'updated_at' => '2023-3-11 08:32:00',
            ],
            [
            'product_id' => '39',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '79',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153264,
            'created_at' => '2023-3-11 08:32:00',
            'updated_at' => '2023-3-11 08:32:00',
            ],//Cancelled/Rejected Products - End
            [//Order Transfers - Begin
            'product_id' => '38',
            'activity' => 'Purchase Order #',
            'adjusted_by' => 'Mark Joseph Manalo',
            'operation_value' => '(+5)',
            'latest_value' => '45',
			'purchase_order_id' => 1000,
			'customer_order_id' => NULL,
            'created_at' => '2023-01-4 00:00:00',
            'updated_at' => '2023-01-4 00:00:00',
            ],
            [
            'product_id' => '35',
            'activity' => 'Purchase Order #',
            'adjusted_by' => 'Mark Joseph Manalo',
            'operation_value' => '(+2)',
            'latest_value' => '42',
			'purchase_order_id' => 1001,
			'customer_order_id' => NULL,
            'created_at' => '2023-01-13 00:00:00',
            'updated_at' => '2023-01-13 00:00:00',
            ],
            [
            'product_id' => '80',
            'activity' => 'Purchase Order #',
            'adjusted_by' => 'Mark Joseph Manalo',
            'operation_value' => '(+1)',
            'latest_value' => '41',
			'purchase_order_id' => 1002,
			'customer_order_id' => NULL,
            'created_at' => '2023-01-13 00:00:00',
            'updated_at' => '2023-01-13 00:00:00',
            ],
            [
            'product_id' => '48',
            'activity' => 'Purchase Order #',
            'adjusted_by' => 'Mark Joseph Manalo',
            'operation_value' => '(+12)',
            'latest_value' => '52',
			'purchase_order_id' => 1003,
			'customer_order_id' => NULL,
            'created_at' => '2023-01-13 00:00:00',
            'updated_at' => '2023-01-13 00:00:00',
            ],
            [
            'product_id' => '141',
            'activity' => 'Purchase Order # ',
            'adjusted_by' => 'Mark Joseph Manalo',
            'operation_value' => '(+15)',
            'latest_value' => '55',
			'purchase_order_id' => 1004,
			'customer_order_id' => NULL,
            'created_at' => '2023-01-13 00:00:00',
            'updated_at' => '2023-01-13 00:00:00',
            ],//Order Transfers - End
            [//March Order - 1
            'product_id' => '80',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '40',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153269,
            'created_at' => '2023-3-12 00:00:00',
            'updated_at' => '2023-3-12 00:00:00',
            ],
            [//March Order - 2
            'product_id' => '80',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '39',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153270,
            'created_at' => '2023-3-14 00:00:00',
            'updated_at' => '2023-3-14 00:00:00',
            ],
            [//March Order - 3
            'product_id' => '80',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '38',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153271,
            'created_at' => '2023-3-16 00:00:00',
            'updated_at' => '2023-3-16 00:00:00',
            ],
            [//March Order - 4
            'product_id' => '80',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '37',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153272,
            'created_at' => '2023-3-18 00:00:00',
            'updated_at' => '2023-3-18 00:00:00',
            ],
            [//March Order - 5
            'product_id' => '80',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '36',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153273,
            'created_at' => '2023-3-20 00:00:00',
            'updated_at' => '2023-3-20 00:00:00',
            ],
            [//April Order - 1
            'product_id' => '94',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-3)',
            'latest_value' => '37',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153274,
            'created_at' => '2023-4-01 00:00:00',
            'updated_at' => '2023-4-01 00:00:00',
            ],
            [//April Order - 2
            'product_id' => '61',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-2)',
            'latest_value' => '37',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153275,
            'created_at' => '2023-4-05 00:00:00',
            'updated_at' => '2023-4-05 00:00:00',
            ],
            [//April Order - 3
            'product_id' => '3',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-10)',
            'latest_value' => '2',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153276,
            'created_at' => '2023-4-11 00:00:00',
            'updated_at' => '2023-4-11 00:00:00',
            ],
            [//April Order - 4
            'product_id' => '16',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-2)',
            'latest_value' => '38',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153277,
            'created_at' => '2023-4-12 00:00:00',
            'updated_at' => '2023-4-12 00:00:00',
            ],
            [//April Order - 5
            'product_id' => '50',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-6)',
            'latest_value' => '34',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153278,
            'created_at' => '2023-4-17 00:00:00',
            'updated_at' => '2023-4-17 00:00:00',
            ],
            [//April Order - 6
            'product_id' => '107',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '39',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153279,
            'created_at' => '2023-4-25 00:00:00',
            'updated_at' => '2023-4-25 00:00:00',
            ],
            [//April Order - 7
            'product_id' => '21',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-5)',
            'latest_value' => '35',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153280,
            'created_at' => '2023-4-28 00:00:00',
            'updated_at' => '2023-4-28 00:00:00',
            ],
            [//May Order - 1
            'product_id' => '81',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-2)',
            'latest_value' => '38',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153281,
            'created_at' => '2023-5-02 00:00:00',
            'updated_at' => '2023-5-02 00:00:00',
            ],
            [//May Order - 2
            'product_id' => '15',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-16)',
            'latest_value' => '24',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153282,
            'created_at' => '2023-5-04 00:00:00',
            'updated_at' => '2023-5-04 00:00:00',
            ],
            [//May Order - 3
            'product_id' => '135',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-2)',
            'latest_value' => '38',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153283,
            'created_at' => '2023-5-06 00:00:00',
            'updated_at' => '2023-5-06 00:00:00',
            ],
            [//May Order - 4
            'product_id' => '58',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-3)',
            'latest_value' => '37',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153284,
            'created_at' => '2023-5-08 00:00:00',
            'updated_at' => '2023-5-08 00:00:00',
            ],
            [//May Order - 5
            'product_id' => '64',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-2)',
            'latest_value' => '38',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153285,
            'created_at' => '2023-5-10 00:00:00',
            'updated_at' => '2023-5-10 00:00:00',
            ],
            [//May Order - 6
            'product_id' => '17',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-20)',
            'latest_value' => '20',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153286,
            'created_at' => '2023-5-12 00:00:00',
            'updated_at' => '2023-5-12 00:00:00',
            ],
             [//Mark 10
            'product_id' => '80',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '35',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153287,
            'created_at' => '2023-5-15 00:00:00',
            'updated_at' => '2023-5-15 00:00:00',
            ],
            [//Mark 10
            'product_id' => '94',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '36',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153287,
            'created_at' => '2023-5-15 00:00:00',
            'updated_at' => '2023-5-15 00:00:00',
            ],
            [//Mark 10
            'product_id' => '61',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '36',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153287,
            'created_at' => '2023-5-15 00:00:00',
            'updated_at' => '2023-5-15 00:00:00',
            ],
            [//Mark 10
            'product_id' => '3',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '1',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153287,
            'created_at' => '2023-5-15 00:00:00',
            'updated_at' => '2023-5-15 00:00:00',
            ],
            [//Mark 10
            'product_id' => '16',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '37',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153287,
            'created_at' => '2023-5-15 00:00:00',
            'updated_at' => '2023-5-15 00:00:00',
            ],
            [//Mark 10
            'product_id' => '50',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '33',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153287,
            'created_at' => '2023-5-15 00:00:00',
            'updated_at' => '2023-5-15 00:00:00',
            ],
            [//Mark 10
            'product_id' => '107',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '38',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153287,
            'created_at' => '2023-5-15 00:00:00',
            'updated_at' => '2023-5-15 00:00:00',
            ],
            [//Mark 10
            'product_id' => '21',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '34',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153287,
            'created_at' => '2023-5-15 00:00:00',
            'updated_at' => '2023-5-15 00:00:00',
            ],
            [//Mark 10
            'product_id' => '81',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '37',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153287,
            'created_at' => '2023-5-15 00:00:00',
            'updated_at' => '2023-5-15 00:00:00',
            ],
            [//Mark 10
            'product_id' => '15',
            'activity' => 'Customer Order with Order ID of ',
            'adjusted_by' => '',
            'operation_value' => '(-1)',
            'latest_value' => '23',
			'purchase_order_id' => NULL,
			'customer_order_id' => 104153287,
            'created_at' => '2023-5-15 00:00:00',
            'updated_at' => '2023-5-15 00:00:00',
            ],
        ]);
    }
}
